#!/bin/sh

set -euo pipefail


#======================================================================================================================
# Run nu (now renamed to nushell) with custom config location.
#======================================================================================================================

CONFIG=/etc/bf/nu
nushell --config ${CONFIG}/config.nu --env-config ${CONFIG}/env.nu
