FROM alpine:<%= ${ALPINE_REVISION} %>

ARG BF_IMAGE
ARG BF_VERSION

ENV \
    # set to 0 to disable additional log output
    BF_DEBUG=1

COPY ./overlay /
COPY ./<%= ${ALPINE_VERSION} %>/overlay /

RUN chmod +x /usr/local/bin/bf-*
RUN bf-install
