FROM alpine:<%= ${ALPINE_REVISION} %>

ARG BF_IMAGE
ARG BF_VERSION

ENV \
    # debug log output
    #   0: disable
    #   1: enable
    BF_DEBUG=0 \
    # path to bf executables
    BF_BIN=/usr/bin/bf

ENV \
    # add bf executables to PATH
    PATH=${BF_BIN}:${PATH}

COPY ./overlay /
COPY ./ESH_BUILD /tmp/
COPY ./<%= ${ALPINE_VERSION} %>/overlay /

RUN chmod +x ${BF_BIN}/bf-install && bf-install

ENTRYPOINT bf-init
