#!/usr/bin/env sh

set -euo pipefail


#======================================================================================================================
# Install Nushell and dependencies.
#======================================================================================================================

echo "Installing Nushell ${NUSHELL_VERSION}."
apk add --no-cache \
    libssl3@edgemain \
    nushell@edgetest>=${NUSHELL_VERSION}


#======================================================================================================================
# Get default configuration files.
#======================================================================================================================

echo "Downloading bfren default configuration files for Nushell ${NUSHELL_VERSION}."
NU_DIR=/root/.config/nushell
mkdir -p ${NU_DIR} && cd ${NU_DIR}
wget https://raw.githubusercontent.com/bfren/nushell/main/${NUSHELL_VERSION}/config.nu
wget https://raw.githubusercontent.com/bfren/nushell/main/${NUSHELL_VERSION}/env.nu


#======================================================================================================================
# Set permissions.
#======================================================================================================================

chmod 0544 /usr/bin/bf/bf-install
chmod 0644 ${NU_DIR}/*
