#!/usr/bin/env sh

set -euo pipefail


#======================================================================================================================
# Test txiki.js version
#======================================================================================================================

echo "Testing txiki.js version."
INSTALLED_VERSION=$(tjs -v)
if [ "${INSTALLED_VERSION}" == "v${TJS_VERSION}" ] ; then
    echo "txiki.js ${INSTALLED_VERSION} detected."
else
    echo "Detected txiki.js version '${INSTALLED_VERSION}' - expecting '${TJS_VERSION}'."
    exit 1
fi


#======================================================================================================================
# Move tjsh executable
#======================================================================================================================

chmod +x /usr/local/bin/tjsh
ln /usr/local/bin/tjsh /bin/tjsh
