#!/usr/bin/env sh

set -euo pipefail


#======================================================================================================================
# Install Nushell dependencies.
#======================================================================================================================

echo "Installing Nushell dependencies."
apk add --no-cache \
    libcrypto3 \
    libgcc \
    libssl3 \
    sqlite-libs


#======================================================================================================================
# Set permissions for installation executable.
#======================================================================================================================

echo "Setting permissions for installation executable."
chmod 0544 /usr/bin/bf/bf-install


#======================================================================================================================
# Test Nushell version.
#======================================================================================================================

echo "Testing Nushell version."
INSTALLED_VERSION=$(nu -v 2> /dev/null)
if [ "${INSTALLED_VERSION}" != "${NUSHELL_VERSION}" ] ; then
    echo "Detected Nushell version '${INSTALLED_VERSION}' - expecting '${NUSHELL_VERSION}'."
    exit 1
fi
