name: update-readme

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | sed "s/bfren\/docker-//")"  >> $GITHUB_ENV
        shell: bash
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push README
        run: |
          jq -n --arg msg "$(<${README.md})" '{"registry":"registry-1.docker.io","full_description": $msg }' | \
          curl https://hub.docker.com/v2/repositories/${{ env.REPOSITORY_NAME }}/ \
          -d @- -X PATCH \
          -H "Content-Type: application/json"

